### ISSUE TITLE
Using slashes in couchdb password

### ISSUE THREAD

**Issue by japel** [burkostya/npm-registry#6]
if I
```bash
docker run --name='npm-registry' -i -t --rm -e 'COUCHDB_ADMIN_LOGIN=admin' -e 'COUCHDB_ADMIN_PASSWORD=test/123!!!' -p 5984:5984 -p 80:80 burkostya/npm-registry:2.6.6
```
I get:
```javascript
Starting couchdb server...
Waiting for couchdb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127  100   127    0     0   4290      0 --:--:-- --:--:-- --:--:--  4379
Database 'registry' created
""

Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

npm ERR! npm-registry-couchapp@2.6.6 start: `bash ./push.sh`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the npm-registry-couchapp@2.6.6 start script.
npm ERR! This is most likely a problem with the npm-registry-couchapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash ./push.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-registry-couchapp
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.8-boot2docker
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start" "--npm-registry-couchapp:couch=http://admin:test/123!!!@localhost:5984/registry"
npm ERR! cwd /opt/couchapp
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/couchapp/npm-debug.log
npm ERR! not ok code 0
```

This does not happen if I choose a password without slashes.

**Comment by burkostya** [comment]
Fixed. Also updated couchapp to 2.6.12. Image will be ready in minutes.
